# Generated by Django 4.0.4 on 2022-05-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='date',
        ),
    ]
