# Generated by Django 4.0.4 on 2022-05-10 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Calculation', '0003_alter_history_algoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='algoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calculation.algos'),
        ),
    ]
