# Generated by Django 4.0.4 on 2022-05-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculation', '0007_rename_algoid_history_aid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='aid',
            new_name='algoId',
        ),
    ]
