# Generated by Django 4.0.4 on 2022-05-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculation', '0008_rename_aid_history_algoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorial',
            name='output',
            field=models.TextField(),
        ),
    ]
